dbfilename redis_queue.rdb
dir /home/arctic_crystal/Repositories/Custom_ERPNext_Erpnext/ERP_Bench/config/pids
pidfile /home/arctic_crystal/Repositories/Custom_ERPNext_Erpnext/ERP_Bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/arctic_crystal/Repositories/Custom_ERPNext_Erpnext/ERP_Bench/config/redis_queue.acl
